<?php

return array(
	'passport' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'kids_passport',
		'dbdriver' => 'mysql',
		'dbprefix' => 'kp_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),

	'pay' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'kids_pay',
		'dbdriver' => 'mysql',
		'dbprefix' => 'kp_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),

	'webgame' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'kids_webgame',
		'dbdriver' => 'mysql',
		'dbprefix' => 'kw_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),
);		

