<?php

return array(
	'passport' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_passport',
		'dbdriver' => 'mysql',
		'dbprefix' => 'sp_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),

	'pay' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_pay',
		'dbdriver' => 'mysql',
		'dbprefix' => 'sp_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),
	'pay' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_webgame',
		'dbdriver' => 'mysql',
		'dbprefix' => 'sw_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),
	'movie' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_movie',
		'dbdriver' => 'mysql',
		'dbprefix' => 'sm_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),

	'spider' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_spider',
		'dbdriver' => 'mysql',
		'dbprefix' => 'ss_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),
	'tbshop' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_tbshop',
		'dbdriver' => 'mysql',
		'dbprefix' => 'st_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	'kidsedu' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_kidsedu',
		'dbdriver' => 'mysql',
		'dbprefix' => 'sk_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),	),
);		

