<?php

return array(
	'passport' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_passport',
		'dbdriver' => 'mysql',
		'dbprefix' => 'sp_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),

	'spider' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_spider',
		'dbdriver' => 'mysql',
		'dbprefix' => 'ss_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),

	'51jiansh' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'studio_51jiansh',
		'dbdriver' => 'mysql',
		'dbprefix' => 's5_',
		'pconnect' => FALSE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
	),
);		

